/* This file was automatically generated by /home/crunch/bin/configure */
#ifndef _CONFIGURE_H_
#define _CONFIGURE_H_

#define CONFIGURE_NAME      "scheme"
#define CONFIGURE_VERSION   "0.1.0"
#define CONFIGURE_ARCH      "x86_64"
#define CONFIGURE_STDIO 1
#define CONFIGURE_STDDEF 1
#define CONFIGURE_STDINT 1
#define CONFIGURE_STDLIB 1

#endif