.TH MICROLISP 1
.SH NAME
microlisp \- microlisp interpreter
.SH SYNOPSIS
.B microlisp
[\fIfile\fR] ...
.SH DESCRIPTION
Lightweight LISP interpreter that follows a minimal Scheme-like dialect.
.SH OPTIONS
.TP 
\fIfile\fR
Load and silently evaluate the source file

.SH AUTHOR
Michael Lazear
.I
@lazear
